services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/restaurant
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - RABBIT_HOST=af4b45659baf047e49724279ab7d29eb-1909975876.us-east-1.elb.amazonaws.com
      - RABBIT_USER=fiap
      - RABBIT_PASSWORD=GpP36_Fiap@2024!
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: